it_news/it_news/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('news.urls', namespace='news')),
    path('admin/', admin.site.urls),
    path('auth/', include('django.contrib.auth.urls')),
]

it_news/news/urls.py
from django.urls import path, include
from .views import NewsListView, NewsCreateView, NewsDetailView, NewsDeleteView
app_name = 'news'

urlpatterns = [
    path('', NewsListView.as_view(), name = 'list_news'),
    path('news/', NewsCreateView.as_view(), name='news' ),
    path('news/<int:pk>/', NewsDetailView.as_view(), name='detail'),
    path('news/<int:pk>/delete', NewsDeleteView.as_view(), name='delete')
]

it_news/news/models.py
from django.contrib.auth import get_user_model
from django.db import models

User = get_user_model()


class News(models.Model):
    
    title = models.CharField(max_length=128,
                             verbose_name='Заголовок'
                             )
    text = models.TextField(verbose_name='Текст новости'
                            )
    image = models.ImageField(blank=True,
                              verbose_name='Изображение'
                              )
    slug = models.SlugField(unique=True,
                            verbose_name='URL'
                            )
    pub_data = models.DateTimeField('Дата публикации',
                                    auto_now_add=True
                                    )
    author = models.ForeignKey(User, 
                               on_delete=models.CASCADE,
                               related_name='author_news',
                               verbose_name='Автор',
                               blank=True
                               )
    class Meta:
        ordering = ['-pub_data']


class Comment(models.Model):
    author = models.ForeignKey(User,
                               on_delete=models.CASCADE,
                               related_name='author_comment',
                               verbose_name='Автор комментария'
                               )
    news = models.ForeignKey(News,
                             on_delete=models.CASCADE,
                             related_name='comment_news',
                             verbose_name='Комментарий новости'
                             )
    text = models.TextField(max_length=300)
    pub_data = models.DateTimeField('Дата публикации',
                                    auto_now_add=True
                                    )

    def __str__(self):
        return self.author

it_news/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

class MyUser(AbstractUser):
    bio = models.TextField('Биография', blank=True)
    company = models.CharField('Коммпания', max_length=30, blank=True)

it_news/news/views.py
from django.shortcuts import render
from django.views.generic import ListView, CreateView, DetailView, DeleteView
from django.urls import reverse_lazy, reverse

from .models import News

class NewsListView(ListView):
    model = News
    ordering = 'id'
    paginate_by = 20
    template_name = 'news/list_news.html'


class NewsCreateView(CreateView):
    model = News
    fields = '__all__'
    template_name = 'news/create_news.html'


    def get_success_url(self):
        return reverse_lazy('news:detail', kwargs={'pk': self.object.pk})


class NewsDetailView(DetailView):
    model = News
    template_name = 'news/detail.html'


class NewsDeleteView(DeleteView):
    model = News
    template_name = 'news/delete.html'
    success_url = reverse_lazy('news:list_news')

it_news/users/views.py
from django.shortcuts import render

# Create your views here.

it_news/templates/base.html
<!DOCTYPE html>
<html>
  <head>
    <link rel="stylesheet"
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x"
      crossorigin="anonymous">
  </head>
  <body class="bg-light">
    {% include "includes/header.html" %}
    <div class="container mt-3">
      {% block content %}
      {% endblock %}
    </div>
  </body>
</html>

it_news/templates/includes/footer.html
<footer>
    <p>Подвал</p>
  </footer> 

it_news/templates/includes/header.html
<header>
    <p>Новости IT</p>
  </header>

it_news/templates/news/create_news.html
{% extends "base.html" %}

{% block content %}
  <form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
  </form>
  {% with data=form.instance %}
    {% if form.is_valid %}
    <h2>ID новой записи в БД: {{ data.id }}</h2>
  {% endif %}

{% endwith %}
{% endblock %}

it_news/templates/news/delete.html
{% extends "base.html" %}
{% block content %}
  <a href="{% url 'news:list_news' %}">На главную</a>
  <h2>Удалить новость?</h2>
  <h3>{{ news.title }}</h3>
  <hr>
  <p>{{  news.text }}</p>
  <form class="form-horizontal" method="post">
    {% csrf_token %}
    <div class="form-actions">
      <button type="submit" class="btn btn-primary" >Удалить</button>
    </div>
  </form>
{% endblock content %}

it_news/templates/news/detail.html
{% extends "base.html" %}
{% block content %}
  <a href="{% url 'news:list_news' %}">На главную</a>
  <hr>
  <article>            
    <h2>{{ news.title }}</h2>            
    <p>{{ news.text|truncatewords:15 }}</p>
    <ul>
    <li>Автор: {{ news.author }}</li>
    <li>Дата: <small>{{ news.pub_data }}</small></li>
    </ul>
  </article>
  <a href="{% url 'news:delete' news.pk %}">Удалить</a>
  <hr>
{% endblock content %}

it_news/templates/news/list_news.html
{% extends "base.html" %}
{% block content %}
  {% for news in object_list %}
    <div class="mt-3">
        <article>            
            <h2>{{ news.title }}</h2>            
            <p>{{ news.text|truncatewords:15 }}</p>
            <ul>
            <li>Автор: {{ news.author }}</li>
            <li>Дата: <small>{{ news.pub_data }}</small></li>
            <li><a href="{% url 'news:detail' news.pk %}">Детали</a></li>            
            </ul>
        </article>
      {% if news.comment_set.all %}
        <ul>
          <li>
            Комментариев: {{ news.comment_set.count }}
          </li>
        </ul>
      {% endif %}
    </div>
  {% endfor %}
{% endblock content %}